### ISSUE TITLE
Building in Eclipse

### ISSUE THREAD

**Issue by BAEGregS** [eyeofnet/Monet#1]
I am trying to build Monet in Eclipse 4.14.0.  I do not understand your comment in the instructions:

"Note that you will have to set your classpath to be able to build the project."

Which classpath needs set?  What does it need to be set to?

**Comment by eyeofnet** [comment]
"set your classpath" is probably the wrong phrase. What it should be is:
"Note that you will have to set your Ghidra installation path to be able to
build the project." The instructions that follow allow you to do that.

**Comment by eyeofnet** [comment]
README.md for project updated

**Comment by BAEGregS** [comment]
Success!


I had to install the gradle package outside of Eclipse and run the gradle from a command line to actually produce the zip file.  Not too worried about that as long as it worked.  It was a spanking new Eclipse install.


Ghidra loaded the zip file and I was able to see an AST graph of a simple buffer copy function.


Thanks for your attention in this matter.


Regards,

Greg


________________________________
